# Generated by Django 5.2.8 on 2025-12-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=10),
        ),
    ]
