# Generated by Django 5.2.8 on 2025-12-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0002_remove_patient_contact_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
